server:
  port: 8080

spring:

  security:
    user:
      name: test
      password: test1234!

  datasource:
    url: jdbc:mysql://{DB_URL}:3306/{SCHEMA_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {DB_USERNAME}
    password: {DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

application:
  jwt:
    secretKey: {JWT_SECRET_KEY}
    expiration: 86400000
    refreshExpiration: 604800000